# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 100

[directory]
truncation_length = 3
style = "bold cyan"
truncate_to_repo = false
read_only = ""

# battery display config
[battery]
disabled = false
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'

[nodejs]
disabled = true

[python]
disabled = true

[package]
disabled = true
